Prune saved shifted instances
talmolab/sleap pull request #1001
Opened 2022-10-19 21:38 UTC by getzze

Following #870, memory is continuously being filled up by saved shifted instances if `save_shifted_instances=True` (which is always the case if using Flow tracker from the GUI before #974 was merged).

This corrects this bug by pruning the dictionary of reference instances older than `track_window` before tracking a new frame.

Sorry for not seeing this bug before, if you are using a version between PR #870 and #974, you can have memory issues if you use the GUI and flow tracking.

2022-10-21 22:03 UTC, roomrys requested changes
Request to add a docstring, but otherwise looks good! Can we add a test for this section of code - I can help write this if you are ready to submit the PR, just let me know.

2022-10-21 23:49 UTC, getzze commented on sleap/nn/tracking.py
> +            del self.shifted_instances[k]
Much better :)

2022-10-21 23:49 UTC, getzze commented on sleap/nn/tracking.py
> +    track_window: int = 5
done

2022-10-21 23:52 UTC, getzze commented
Thanks for reviewing the commit so fast!
I pushed the changes you proposed. 
Regarding the tests, I tried to write them some time ago, but I had a hard time figuring out how to create a mock video and all...

2022-10-24 23:30 UTC, roomrys approved these changes

2022-10-24 23:31 UTC, merged