Added frame chunk method in labeling suggestions
talmolab/sleap pull request #1007
Opened 2022-10-23 19:42 UTC by hsingchien

### Description
PR 3/3 for #977 
Added `frame chunk` method in labeling suggestions. User can add desired number of frame chunks for labeling suggestion. Then user can predict on these frames (select suggested frames in inference prompt). This is an enhancement to the issue discussed in #633 

### Types of changes

- [ ] Bugfix
- [x] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?
[list open issues here]

### Outside contributors checklist

- [x] Review the [guidelines for contributing](https://github.com/talmolab/sleap/blob/develop/docs/CONTRIBUTING.md) to this repository
- [ ] Read and sign the [CLA](https://github.com/talmolab/sleap/blob/develop/sleap-cla.pdf) and add yourself to the [authors list](https://github.com/talmolab/sleap/blob/develop/AUTHORS)
- [x] Make sure you are making a pull request against the **develop** branch (not *main*). Also you should start *your branch* off *develop*
- [x] Add tests that prove your fix is effective or that your feature works
- [ ] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP!
:heart:

2022-11-07 23:11 UTC, roomrys commented
Hi @hsingchien,

Just checking in and seeing if this PR is ready for review?

Thanks,
Liezl

2022-11-07 23:26 UTC, hsingchien commented
Marked ready for review. Sorry for the late response, I thought the PR draft would be pre-reviewed first before it is ready.

2022-11-08 01:12 UTC, roomrys requested changes
Nice feature! Functionally, it works like a charm. Main comment is that I don't think we need a new `UpdateTopic` - we should just be able to use the `UpdateTopic.video`. There are a few more suggestions throughout. Let me know if you want any help implementing!

2022-11-08 01:12 UTC, roomrys commented on sleap/gui/suggestions.py
> +            # make sure when targeting all videos the from and to do not exceed frame number
Nitpick: [google-style comments](https://google.github.io/styleguide/pyguide.html#386-punctuation-spelling-and-grammar)
```suggestion
            # Make sure when targeting all videos the from and to do not exceed frame number
```

2022-11-08 01:12 UTC, roomrys commented on sleap/gui/suggestions.py
> +            # generate list of frame numbers
Nitpick: [google-style comments](https://google.github.io/styleguide/pyguide.html#386-punctuation-spelling-and-grammar)
```suggestion

            # Generate a list of frame numbers
```

2022-11-08 07:12 UTC, hsingchien commented on tests/gui/test_app.py
> +    cur_video_framenum = cur_video.num_frames
Thanks for pointing out!

2022-11-08 07:13 UTC, hsingchien commented on sleap/gui/app.py
> +            frame_from_spinbox.setMaximum(cur_video_framenum)
Spinbox update is now under UpdateTopic.video

2022-11-08 07:15 UTC, hsingchien commented on sleap/gui/suggestions.py
> +        proposed_suggestions = []
Doc string moved up. 
Validation failure now returns empty list.

2022-11-09 04:27 UTC, hsingchien commented on tests/gui/test_suggestions.py
> +            "frame_to": 1000,
Changed to 20

2022-11-10 19:53 UTC, merged