Add Option to Export CSV
talmolab/sleap pull request #1438
Opened 2023-08-04 21:14 UTC by gitttt-1234

### Description
Add an option to export the analysis file in CSV format

### Types of changes

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?
[list open issues here]

### Outside contributors checklist

- [ ] Review the [guidelines for contributing](https://github.com/talmolab/sleap/blob/develop/docs/CONTRIBUTING.md) to this repository
- [ ] Read and sign the [CLA](https://github.com/talmolab/sleap/blob/develop/sleap-cla.pdf) and add yourself to the [authors list](https://github.com/talmolab/sleap/blob/develop/AUTHORS)
- [ ] Make sure you are making a pull request against the **develop** branch (not *main*). Also you should start *your branch* off *develop*
- [ ] Add tests that prove your fix is effective or that your feature works
- [ ] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP!
:heart:

2023-08-07 20:34 UTC, roomrys reviewed
Possible to combine `ExportAnaliysisFile` and `ExportCSVFile`?

2023-08-07 22:29 UTC, gitttt-1234 commented on sleap/gui/commands.py
> +class ExportCSVFile(AppCommand):
Hi,
yes it was almost the same. I changed the code and combined the classes, will push the changes in my next commit

2023-08-08 16:20 UTC, roomrys requested changes

2023-08-08 16:20 UTC, roomrys commented on tests/io/test_formats.py
> +    filename = os.path.join(tmpdir, "analysis.csv")
Prefer pathlib

2023-08-08 16:20 UTC, roomrys commented on tests/io/test_formats.py
> +
Add test fixture artifact with correct CSV for comparison

2023-08-09 22:20 UTC, roomrys reviewed
Good job on condensing the classes. 

I feel like we can condense even further though and use some of the variable for user selection downstream in the FileDialog... ie. instead of having a two buttons for Export Analysis CSV and Export Analysis HDF5, we have one button Export Analysis and allow the user to select the export format as csv downstream in the FileDialog.... The only trouble would be specifying the default extension to use when exporting analysis for all files (and only selecting a folder via the FileDialog...).

What do you think?

2023-08-09 22:20 UTC, roomrys commented on sleap/info/write_tracking_h5.py
> +    # find frames with at least one animal tracked
Nit: google style comments
```suggestion
    # Find frames with at least one animal tracked.
```

2023-08-09 22:20 UTC, roomrys commented on sleap/io/format/csv.py
> +"""
Nit: google style docstrings

```suggestion
"""Adaptor for writing SLEAP analysis as csv."""
```

2023-08-09 22:20 UTC, roomrys commented on sleap/io/format/csv.py
> +    # 1.2 adds track score to read and write functions
```suggestion
    FORMAT_ID = 1.0

    # 1.0 initial implementation
```

2023-08-09 22:20 UTC, roomrys commented on sleap/info/write_tracking_h5.py
> +"""Generate an HDF5/ CSV file with track occupancy and point location data.
```suggestion
"""Generate an HDF5 or CSV file with track occupancy and point location data.
```

2023-08-10 23:29 UTC, roomrys approved these changes

2023-08-10 23:29 UTC, merged