Ramiz/add doubleclick functionality unlinkvideotable
talmolab/sleap pull request #1763
Opened 2024-05-06 22:07 UTC by ramizhajj1

### Description
[describe your changes here]

### Types of changes

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?
[list open issues here]

### Outside contributors checklist

- [ ] Review the [guidelines for contributing](https://github.com/talmolab/sleap/blob/develop/docs/CONTRIBUTING.md) to this repository
- [ ] Read and sign the [CLA](https://github.com/talmolab/sleap/blob/develop/sleap-cla.pdf) and add yourself to the [authors list](https://github.com/talmolab/sleap/blob/develop/AUTHORS)
- [ ] Make sure you are making a pull request against the **develop** branch (not *main*). Also you should start *your branch* off *develop*
- [ ] Add tests that prove your fix is effective or that your feature works
- [ ] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP!
:heart:

2024-05-08 19:11 UTC, roomrys requested changes
There must be something up with the load_video in videos.py. I would expect the unlinked_video to load, but it doesn't appear to be loading!

2024-05-17 23:05 UTC, ramizhajj1 commented
I re-encoded the video.mp4 files using this command: `ffmpeg -y -i "input.mp4" -c:v libx264 -pix_fmt yuv420p -preset superfast -crf 23 "output.mp4"` and it seems that the videos are correctly loading when I double click them on the unlinked videos table.

https://github.com/talmolab/sleap/assets/122569822/62f20429-cab0-4621-a070-7f555a80e194

2024-05-21 14:19 UTC, talmo requested changes

2024-05-21 14:19 UTC, talmo commented on Anaconda3-2023.04-MacOSX-x86_64.sh
Remove

2024-05-21 14:19 UTC, talmo commented on sleap/gui/dataviews.py
> +            print("Activated:", self.row_name, self.state[self.row_name])
Remove debugging print

2024-05-24 15:54 UTC, roomrys requested changes
Remove some of the extra files please. Also, I don't see that the videos were reencoded. Can you add the re-encoded videos here (their binaries should have changed which should have been picked up by git).

2024-05-24 15:54 UTC, roomrys commented on sleap/gui/app.py
> +    main([ds])
```suggestion
```

2024-05-24 15:54 UTC, roomrys commented on sleap/gui/scripts/reencoder.py
I would `git rm` this file, but definitely keep it around (maybe in your gists for now). This might make for a nice CLI command that we ship with sleap, but if it is added, it should be added on the develop branch not the MV GUI branch.

2024-05-29 23:11 UTC, roomrys approved these changes

2024-05-29 23:42 UTC, merged