(4a -> 4) Add functionality s.t. when double click on row in `CamerasTable`, we switched to the linked video (if any)
talmolab/sleap pull request #1825
Opened 2024-06-23 18:07 UTC by 7174Andy

### Description
When a user double-clicks a row in `CamerasTable`, SLEAP will automatically sets the `state["camera"]` to the selected camera and switch the video to the video that is linked to the selected camera. 

### Types of changes

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Outside contributors checklist

- [ ] Review the [guidelines for contributing](https://github.com/talmolab/sleap/blob/develop/docs/CONTRIBUTING.md) to this repository
- [ ] Read and sign the [CLA](https://github.com/talmolab/sleap/blob/develop/sleap-cla.pdf) and add yourself to the [authors list](https://github.com/talmolab/sleap/blob/develop/AUTHORS)
- [ ] Make sure you are making a pull request against the **develop** branch (not *main*). Also you should start *your branch* off *develop*
- [ ] Add tests that prove your fix is effective or that your feature works
- [ ] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP!
:heart:

2024-06-23 18:08 UTC, 7174Andy commented on sleap/gui/app.py
> +    main([ds])
Will delete them when ready to merge

2024-06-26 23:01 UTC, roomrys requested changes
It works! But this logic should not be placed inside `GenericTableView`.

2024-06-26 23:01 UTC, roomrys commented on sleap/gui/dataviews.py
> +                    self.state["video"] = session.get_video(self.getSelectedRowItem())
Good logic, but I dislike the placement inside `GENERICTableView` which is supposed to be... generic. A new class off of `GenericTableView`  where we override the `GenericTableView.activateSelected` is a good option. Or we could delegate this over to QtVideoPlayer where we do a similar thing for the `"unlinked_video"` `GuiState` key:
https://github.com/talmolab/sleap/blob/a32d68a1c116584c8950fde841310e77cc71ac99/sleap/gui/widgets/video.py#L278-L283

2024-06-28 17:18 UTC, gitttt-1234 submitted a review, later dismissed

2024-07-01 17:36 UTC, roomrys approved these changes

2024-07-01 18:06 UTC, merged