Add read/write adaptor for ndx-pose
talmolab/sleap pull request #835
Opened 2022-07-12 03:45 UTC by roomrys

### Description
Add read/write adaptor for `ndx-pose`. Only reads/writes predicted instances. Next steps include: 
- means to read/write training data as well 
- integration with `sleap-io` repo

### Types of changes

- [ ] Bugfix
- [x] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?
N/A

### Outside contributors checklist

- [ ] Review the [guidelines for contributing](https://github.com/talmolab/sleap/wiki/Developer-Guide) to this repository
- [ ] Read and sign the [CLA](https://github.com/talmolab/sleap/blob/develop/sleap-cla.pdf) and add yourself to the [authors list](https://github.com/talmolab/sleap/blob/develop/AUTHORS)
- [ ] Make sure you are making a pull request against the **develop** branch (not *main*). Also you should start *your branch* off *develop*
- [ ] Add tests that prove your fix is effective or that your feature works
- [ ] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP!
:heart:

2022-07-12 16:08 UTC, talmo requested changes

2022-07-12 16:08 UTC, talmo commented on requirements.txt
> +certifi>=2017.4.17,<=2021.10.8
Do we need to version fence this on the upper end? I think some people were having issues with `certifi`

2022-07-12 16:08 UTC, talmo commented on sleap/io/dataset.py
> +        get_confidence: bool = False,
Missing docstring for this, and also I'd name it `return_confidence` instead

2022-07-12 16:08 UTC, talmo commented on sleap/io/format/ndx_pose.py
> +                    # scorer="DLC_resnet50_openfieldOct30shuffle1_1600",
Delete comment or include metadata from `labels.provenance` if available

2022-07-12 17:13 UTC, roomrys commented on sleap/io/format/ndx_pose.py
> +                    # scorer="DLC_resnet50_openfieldOct30shuffle1_1600",
`scorer=str(labels.provenance)`

2022-07-15 00:07 UTC, roomrys reviewed
Self-review with a few requested changes

2022-07-15 00:07 UTC, roomrys commented on sleap/gui/commands.py
> +            filters = [f"(*.{params['extension']})"]
Maybe we can pass in an adaptor class in `params["extensions"]` and then use `params["extensions"].default_ext` for the suffix and `params["extensions"].all_ext` for the filters. Also, in that case, `"extensions"` -> `"adaptor"`.

2022-07-15 00:07 UTC, roomrys commented on sleap/gui/commands.py
> +        filters = ["NWB (*.nwb)"]
Should really reference the `NXDPoseAdaptor` class here and use `NDXAdaptor.name` with `NDXAdaptor.all_exts`

2022-07-15 00:07 UTC, roomrys commented on sleap/gui/commands.py
> +            extension = filename.split(".")[-1]
The `PurePath(...).suffix` method returns the extension with `.` still attached

2022-07-15 00:25 UTC, roomrys commented on sleap/gui/commands.py
> +            extension = filename.split(".")[-1]
use pathlib

2022-07-15 17:46 UTC, talmo approved these changes

2022-07-15 17:54 UTC, merged