Append Unique Suggestions
talmolab/sleap pull request #874
Opened 2022-07-29 18:54 UTC by jiayinghsu

### Description
Updated suggestions.py and test_suggestions.py for appending unique suggestions every time when users click the "generate suggestions" button. 

### Types of changes

- [x] Bugfix
- [x] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?
#838 

### Outside contributors checklist

- [ ] Review the [guidelines for contributing](https://github.com/talmolab/sleap/wiki/Developer-Guide) to this repository
- [ ] Read and sign the [CLA](https://github.com/talmolab/sleap/blob/develop/sleap-cla.pdf) and add yourself to the [authors list](https://github.com/talmolab/sleap/blob/develop/AUTHORS)
- [x] Make sure you are making a pull request against the **develop** branch (not *main*). Also you should start *your branch* off *develop*
- [x] Add tests that prove your fix is effective or that your feature works
- [ ] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP!
:heart:

2022-07-29 21:00 UTC, roomrys requested changes
Some superficial changes requested for the first round

2022-07-29 21:00 UTC, roomrys commented on tests/gui/test_suggestions.py
> +    # track_c = Track(0, "c")
Remove

2022-08-16 22:02 UTC, roomrys requested changes
Should be using a set difference '-' instead of symmetric difference `^`. Also, we need to account for different videos in `image_feature_based_method`.

2022-09-02 22:46 UTC, roomrys approved these changes
looks good to me

2022-09-06 16:53 UTC, talmo approved these changes
LGTM!

2022-09-06 17:01 UTC, merged